"""add phone_encrypted back to profiles

Revision ID: 07954f8fa416
Revises: 432955958e19
Create Date: 2026-05-11 08:34:57.311659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07954f8fa416'
down_revision: Union[str, None] = '432955958e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_encrypted', sa.Text(), nullable=True, comment='Mã hóa pgcrypto — SĐT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone_encrypted')
    # ### end Alembic commands ###
