"""add_expires_at_to_consent_permissions

Revision ID: 0aac322b299d
Revises: 07954f8fa416
Create Date: 2026-05-20 07:01:19.875982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aac322b299d'
down_revision: Union[str, None] = '07954f8fa416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_permissions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = vĩnh viễn. Khi hết hạn, quyền tự động vô hiệu.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent_permissions', 'expires_at')
    # ### end Alembic commands ###
