"""remove phone_encrypted from profiles

Revision ID: 26c90af1fec5
Revises: dee690ba0a46
Create Date: 2026-05-10 17:06:23.282775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c90af1fec5'
down_revision: Union[str, None] = 'dee690ba0a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender', sa.String(length=10), server_default=sa.text("'NAM'"), nullable=False))
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'gender')
    # ### end Alembic commands ###
