"""add_family_allergies_avcines_v2_2

Revision ID: 8028cd5949d2
Revises: 840baf4a1b8e
Create Date: 2026-06-14 06:52:23.831663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8028cd5949d2'
down_revision: Union[str, None] = '840baf4a1b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False, comment='Tên chất gây dị ứng/thuốc/thức ăn'),
    sa.Column('severity', sa.String(length=50), nullable=True, comment='Mức độ: mild, moderate, severe'),
    sa.Column('reaction', sa.Text(), nullable=True, comment='Biểu hiện'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú thêm'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_user_id'), 'allergies', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False, comment='Người giám hộ (cha/mẹ)'),
    sa.Column('dependent_id', sa.UUID(), nullable=False, comment='Người phụ thuộc (trẻ em)'),
    sa.Column('relationship', sa.String(length=50), nullable=False, comment='Ví dụ: cha, mẹ, người giám hộ'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependent_id')
    )
    op.create_table('vaccines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=200), nullable=False, comment='Tên vaccine'),
    sa.Column('disease_targeted', sa.String(length=200), nullable=True, comment='Bệnh phòng ngừa'),
    sa.Column('dose_number', sa.String(length=50), nullable=True, comment='Mũi số mấy'),
    sa.Column('vaccination_date', sa.Date(), nullable=False, comment='Ngày tiêm'),
    sa.Column('administered_by', sa.String(length=200), nullable=True, comment='Nơi tiêm / Người tiêm'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú thêm'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_user_id'), 'vaccines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccines_user_id'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_allergies_user_id'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
