"""add_patient_documents_table

Revision ID: 8dbbdc83d1eb
Revises: 840baf4a1b8e
Create Date: 2026-06-15 15:30:08.738216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dbbdc83d1eb'
down_revision: Union[str, None] = '840baf4a1b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_allergies_user_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_vaccines_user_id'), table_name='vaccines')
    op.drop_table('vaccines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vaccine_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='T├¬n vaccine'),
    sa.Column('disease_targeted', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Bß╗çnh ph├▓ng ngß╗½a'),
    sa.Column('dose_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='M┼⌐i sß╗æ mß║Ñy'),
    sa.Column('vaccination_date', sa.DATE(), autoincrement=False, nullable=False, comment='Ng├áy ti├¬m'),
    sa.Column('administered_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='N╞íi ti├¬m / Ng╞░ß╗¥i ti├¬m'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Ghi ch├║ th├¬m'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('vaccines_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccines_pkey'))
    )
    op.create_index(op.f('ix_vaccines_user_id'), 'vaccines', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('guardian_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ng╞░ß╗¥i gi├ím hß╗Ö (cha/mß║╣)'),
    sa.Column('dependent_id', sa.UUID(), autoincrement=False, nullable=False, comment='Ng╞░ß╗¥i phß╗Ñ thuß╗Öc (trß║╗ em)'),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='V├¡ dß╗Ñ: cha, mß║╣, ng╞░ß╗¥i gi├ím hß╗Ö'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['profiles.id'], name=op.f('family_members_dependent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_id'], ['profiles.id'], name=op.f('family_members_guardian_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('family_members_pkey')),
    sa.UniqueConstraint('dependent_id', name=op.f('family_members_dependent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergen', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='T├¬n chß║Ñt g├óy dß╗ï ß╗⌐ng/thuß╗æc/thß╗⌐c ─ân'),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Mß╗⌐c ─æß╗Ö: mild, moderate, severe'),
    sa.Column('reaction', sa.TEXT(), autoincrement=False, nullable=True, comment='Biß╗âu hiß╗çn'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Ghi ch├║ th├¬m'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('allergies_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_index(op.f('ix_allergies_user_id'), 'allergies', ['user_id'], unique=False)
    op.drop_table('patient_documents')
    # ### end Alembic commands ###
