"""add_blood_type_check_constraint

Revision ID: 971dcd67e1ac
Revises: b26d8d7ce31e
Create Date: 2026-06-06 03:57:26.778547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '971dcd67e1ac'
down_revision: Union[str, None] = 'b26d8d7ce31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_health_records', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Metric payload, shaped by metric_type',
               existing_comment='Dữ liệu đo lường, cấu trúc tùy theo metric_type',
               existing_nullable=False)
    op.alter_column('manual_health_records', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Optional measuring device name',
               existing_comment='Tên thiết bị đo. VD: Máy đo huyết áp Omron HEM-7156',
               existing_nullable=True)
    op.alter_column('manual_health_records', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional patient notes',
               existing_comment='Ghi chú tùy chọn của bệnh nhân',
               existing_nullable=True)
    op.alter_column('manual_health_records', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Actual measurement time',
               existing_comment='Thời điểm đo thực tế',
               existing_nullable=False)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'ck_profiles_blood_type'
                  AND conrelid = 'profiles'::regclass
            ) THEN
                ALTER TABLE profiles
                ADD CONSTRAINT ck_profiles_blood_type
                CHECK (blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'));
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_health_records', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm đo thực tế',
               existing_comment='Actual measurement time',
               existing_nullable=False)
    op.alter_column('manual_health_records', 'notes',
               existing_type=sa.TEXT(),
               comment='Ghi chú tùy chọn của bệnh nhân',
               existing_comment='Optional patient notes',
               existing_nullable=True)
    op.alter_column('manual_health_records', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên thiết bị đo. VD: Máy đo huyết áp Omron HEM-7156',
               existing_comment='Optional measuring device name',
               existing_nullable=True)
    op.alter_column('manual_health_records', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Dữ liệu đo lường, cấu trúc tùy theo metric_type',
               existing_comment='Metric payload, shaped by metric_type',
               existing_nullable=False)
    op.execute("ALTER TABLE profiles DROP CONSTRAINT IF EXISTS ck_profiles_blood_type")
    # ### end Alembic commands ###
