"""add_manual_health_records_table

Revision ID: b26d8d7ce31e
Revises: 0351ddbdf002
Create Date: 2026-06-05 15:12:59.258722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26d8d7ce31e'
down_revision: Union[str, None] = '0351ddbdf002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_health_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dữ liệu đo lường, cấu trúc tùy theo metric_type'),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment='Tên thiết bị đo. VD: Máy đo huyết áp Omron HEM-7156'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú tùy chọn của bệnh nhân'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm đo thực tế'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_health_records_user_recorded', 'manual_health_records', ['user_id', 'recorded_at'], unique=False)
    op.create_index('ix_manual_health_records_user_type', 'manual_health_records', ['user_id', 'metric_type'], unique=False)
    op.drop_constraint(op.f('fk_profiles_users'), 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_profiles_users'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index('ix_manual_health_records_user_type', table_name='manual_health_records')
    op.drop_index('ix_manual_health_records_user_recorded', table_name='manual_health_records')
    op.drop_table('manual_health_records')
    # ### end Alembic commands ###
