"""initial_schema

Revision ID: dee690ba0a46
Revises: 
Create Date: 2026-05-05 09:46:35.606783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dee690ba0a46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='References auth.users'),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=True, comment='Mã hóa pgcrypto'),
    sa.Column('cccd_encrypted', sa.Text(), nullable=True, comment='Mã hóa pgcrypto — CCCD'),
    sa.Column('blood_type', sa.String(length=5), nullable=True, comment='VD: O+, AB-'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='VD: Penicillin, Aspirin'),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True, comment='SĐT người thân'),
    sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"show_blood_type": true, "show_allergies": true, "show_emergency_contact": true}\'::jsonb'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.ARRAY(sa.Text()), nullable=False, comment='Tập con của requested_scope'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_consent_permissions_active', 'consent_permissions', ['doctor_id', 'patient_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('consent_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('requested_scope', postgresql.ARRAY(sa.Text()), nullable=False, comment='Gồm: blood_type, allergies, emergency_contact, medical_records, prescriptions, diaries, heart_rate, step_count, respiratory_rate'),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_requests_patient_status', 'consent_requests', ['patient_id', 'status'], unique=False)
    op.create_table('data_access_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True, comment='Chủ sở hữu dữ liệu'),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_access_logs_target_time', 'data_access_logs', ['target_user_id', 'created_at'], unique=False)
    op.create_table('diaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='Ghi chép tự do bằng chữ'),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='VD: [{"name": "Đau đầu", "severity": 7}, {"name": "Chóng mặt", "severity": 4}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('certificate_url', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'pending_verification'"), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='Admin who verified'),
    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('emergency_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = vĩnh viễn, không hết hạn'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete — vô hiệu hóa token'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_emergency_tokens_token', 'emergency_tokens', ['token'], unique=False)
    op.create_index('ix_emergency_tokens_user_active', 'emergency_tokens', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm đo, có thể khác thời điểm gửi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_metrics_user_recorded', 'health_metrics', ['user_id', 'recorded_at'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Mảng URLs: ["url1", "url2"]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['doctor_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='Trỏ đến bản ghi liên quan tùy type'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ghi chú chung của đơn thuốc'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['doctor_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_access_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm quét QR'),
    sa.ForeignKeyConstraint(['token_id'], ['emergency_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emergency_access_logs_token_time', 'emergency_access_logs', ['token_id', 'accessed_at'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=500), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_times', postgresql.ARRAY(sa.Time()), nullable=False, comment="Mảng các khung giờ uống thuốc. VD: ['08:00', '13:00', '20:00']"),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft Delete'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prescription_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False, comment='Ngày dự kiến uống thuốc'),
    sa.Column('scheduled_time', sa.Time(), nullable=False, comment='Giờ dự kiến uống thuốc'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'untaken'"), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True, comment="Chỉ có giá trị khi status = 'taken'"),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prescription_logs_item_schedule', 'prescription_logs', ['prescription_item_id', 'scheduled_date', 'scheduled_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescription_logs_item_schedule', table_name='prescription_logs')
    op.drop_table('prescription_logs')
    op.drop_table('prescription_items')
    op.drop_index('ix_emergency_access_logs_token_time', table_name='emergency_access_logs')
    op.drop_table('emergency_access_logs')
    op.drop_table('prescriptions')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('medical_records')
    op.drop_index('ix_health_metrics_user_recorded', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('ix_emergency_tokens_user_active', table_name='emergency_tokens', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_emergency_tokens_token', table_name='emergency_tokens')
    op.drop_table('emergency_tokens')
    op.drop_table('doctors')
    op.drop_table('diaries')
    op.drop_index('ix_data_access_logs_target_time', table_name='data_access_logs')
    op.drop_table('data_access_logs')
    op.drop_index('ix_consent_requests_patient_status', table_name='consent_requests')
    op.drop_table('consent_requests')
    op.drop_index('uq_consent_permissions_active', table_name='consent_permissions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('consent_permissions')
    op.drop_table('profiles')
    # ### end Alembic commands ###
